### ISSUE TITLE
cctl pause throws error in user-code

### ISSUE THREAD

**Issue by lliu11** [coachbots/cctl#92]
When using `cctl pause` an error is thrown in the user code 

**To Reproduce**
1. Run `cctl pause`
```
Traceback (most recent call last):
  File "/usr/local/bin/cctl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cctl/__main__.py", line 25, in main
    return asyncio.run(cli.exec_command(args, conf))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/cctl/cli/commands.py", line 174, in pause_handle
    await asyncio.gather(*(
  File "/usr/local/lib/python3.8/dist-packages/cctl/api/cctld.py", line 211, in set_user_code_running
    self.__class__._raise_error_code(response)
  File "/usr/local/lib/python3.8/dist-packages/cctl/api/cctld.py", line 106, in _raise_error_code
    raise CCTLDRespInvalidState(response.body)
cctl.api.cctld.CCTLDRespInvalidState: Did not receive a reply from the Coachbot.
```

Run `tail -f /var/log/syslog | grep coach-os | grep -v DEBUG | grep SYS-ERROR`
Output: 
```
Oct 25 17:29:47 192.168.1.9 coach-os[402] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.8 coach-os[405] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.13 coach-os[402] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.16 coach-os[397] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.28 coach-os[401] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.24 coach-os[402] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.27 coach-os[401] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:47 192.168.1.14 coach-os[402] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.17 coach-os[403] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.44 coach-os[401] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.31 coach-os[402] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.33 coach-os[404] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.37 coach-os[401] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.52 coach-os[403] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.49 coach-os[403] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.46 coach-os[402] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.34 coach-os[403] [SYS-ERROR]: An error has occurred in user-code: semaphore or lock released too many times.#012Traceback (most recent call last):#012  File "/home/pi/control/usr.py", line 572, in usr_program#012    usr_code.usr(myrobot)#012  File "/home/pi/control/usr_code.py", line 179, in usr#012    robot.delay()#012  File "/home/pi/control/usr.py", line 523, in delay#012    self._lock.release()#012ValueError: semaphore or lock released too many times
Oct 25 17:29:48 192.168.1.49 coach-os[403] [SYS-ERROR]: Could not initialize the user code due to semaphore or lock released too many times.
```

**Expected behavior**
`cctl pause` shouldn't throw any errors

**Comment by markovejnovic** [comment]
Closing since this is a `coach-os` bug
